spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/apidb
    username: apidbuser
    password: apidbuser

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org:
      springframework:
        security:
          web: trace

com:
  rootable:
    upload:
      path: upload # 업로드 파일을 관리할 디렉토리

jwt:
  secret: 1f75ab39d90b79e185ce0e0dbeaf852d64cda0e7436e27afa5afc04de53cedd34e369c56c595e793681770005002fa3d0f08c6e86179b8ea27c16bedcf64bba9
